import {createRegistry} from './graph/registry.js';
import {coreDefinitions} from './modules/core-definitions.js';
import {compilePatchGraph} from './graph/compile.js';
import {HistoryController} from './state/history.js';
import {defaultPatch} from './persistence/presets.js';
import {factoryPresets,getFactoryPreset} from './presets/factory.js';
import {serializePatch,deserializePatch} from './persistence/patch-schema.js';
import {saveLocal,loadLocal} from './persistence/patch-store.js';
import {AudioEngine} from './engine/audio-engine.js';
import {ComputerKeyboard} from './input/computer-keyboard.js';
import {connectMidi} from './input/midi.js';
import {renderWorkspace} from './ui/workspace.js';
import {renderKeyboard} from './ui/keyboard-view.js';
import {VisualizationScheduler} from './visual/scheduler.js';
import {drawWaveform} from './visual/waveform.js';
import {drawSpectrum} from './visual/spectrum.js';
import {DiagnosticsLog,collectDiagnostics} from './diagnostics/diagnostics.js';

const $=s=>document.querySelector(s);
let registry,history,engine,scheduler,keyboard,midiState={available:false,reason:'not-initialized'},idSeq=0,masterMuted=false;
const log=new DiagnosticsLog(50);
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function newId(type){return `${type}-${Date.now().toString(36)}-${(++idSeq).toString(36)}`}
function moduleState(def){const params={};for(const p of def.parameters)params[p.id]=p.default;return{id:newId(def.typeId),type:def.typeId,position:{x:80+Math.random()*220,y:80+Math.random()*220},params}}
function status(text){const d=$('#diagnostics');if(d)d.textContent=text}
function diagnosticsDocument(){return collectDiagnostics({engine,patch:history?.state,midi:midiState,visualization:scheduler?.diagnostics?.()??{},log})}
async function rebuildIfRunning(){if(!engine.started)return;try{await engine.applyCompiledGraph(compilePatchGraph(history.state,registry));status('Graph active');log.push('info','graph activated',{modules:history.state.modules.length,connections:history.state.connections.length})}catch(e){status(`Graph rejected: ${e.message}`);log.push('error','graph rejected',{message:e.message})}}
function renderLibrary(){const root=$('#module-library');root.querySelectorAll('button[data-add]').forEach(x=>x.remove());for(const d of registry.list()){if(d.typeId==='master'&&history.state.modules.some(m=>m.type==='master'))continue;const b=document.createElement('button');b.dataset.add=d.typeId;b.textContent=`+ ${d.name}`;b.onclick=()=>{history.apply({type:'addModule',module:moduleState(d)});log.push('info','module added',{type:d.typeId});render();rebuildIfRunning()};root.append(b)}}
function connectionSignal(c){const m=history.state.modules.find(x=>x.id===c.from.module);if(!m)return'unknown';return registry.get(m.type).ports.find(p=>p.id===c.from.port)?.signal??'unknown'}
function renderConnections(){const root=$('#connection-list');root.innerHTML='';if(!history.state.connections.length){root.textContent='No cables';return}for(const c of history.state.connections){const signal=connectionSignal(c),row=document.createElement('div');row.className='connection-row';const title=document.createElement('div');title.className='connection-title';title.textContent=`${c.from.module}:${c.from.port} → ${c.to.module}:${c.to.port}`;row.append(title);const controls=document.createElement('div');controls.className='connection-controls';if(signal==='control'){const amount=document.createElement('input');amount.type='range';amount.min='0';amount.max='2';amount.step='.01';amount.value=Number.isFinite(c.amount)?Math.abs(c.amount):1;amount.setAttribute('aria-label',`Modulation amount for ${c.id}`);amount.oninput=()=>{history.apply({type:'updateConnection',id:c.id,patch:{amount:Number(amount.value)}});rebuildIfRunning()};const polarity=document.createElement('button');polarity.type='button';polarity.textContent=c.polarity===-1?'−':'+';polarity.setAttribute('aria-label',`Toggle modulation polarity for ${c.id}`);polarity.onclick=()=>{history.apply({type:'updateConnection',id:c.id,patch:{polarity:c.polarity===-1?1:-1}});render();rebuildIfRunning()};controls.append(amount,polarity)}else{const spacer=document.createElement('span');spacer.textContent=signal;controls.append(spacer)}const remove=document.createElement('button');remove.type='button';remove.textContent='Disconnect';remove.onclick=()=>{history.apply({type:'disconnect',id:c.id});render();rebuildIfRunning()};controls.append(remove);row.append(controls);root.append(row)}}
function syncMasterControls(){const master=history.state.modules.find(m=>m.type==='master'),volume=$('#master-volume');if(master&&volume)volume.value=String(master.params?.gain??.8);const mute=$('#master-mute');if(mute){mute.setAttribute('aria-pressed',String(masterMuted));mute.textContent=masterMuted?'Unmute':'Mute'}}
function render(){renderWorkspace($('#workspace'),history.state,registry,{onParam:(id,param,value)=>{history.apply({type:'setParam',id,param,value});engine.setParameter(id,param,value)},onMove:(id,x,y)=>{history.apply({type:'moveModule',id,x,y});render()},onRemove:id=>{history.apply({type:'removeModule',id});render();rebuildIfRunning()},onDuplicate:id=>{history.apply({type:'duplicateModule',id,newId:newId(history.state.modules.find(m=>m.id===id)?.type||'module')});render();rebuildIfRunning()},onConnect:(from,to)=>{const signal=from.signal;history.apply({type:'connect',connection:{id:newId('cable'),from:{module:from.module,port:from.port},to:{module:to.module,port:to.port},...(signal==='control'?{amount:1,polarity:1}:{})}});try{compilePatchGraph(history.state,registry)}catch(e){history.undo();status(`Cable rejected: ${e.message}`);render();return}render();rebuildIfRunning()}});renderLibrary();renderConnections();syncMasterControls();status(`${history.state.modules.length} modules · ${history.state.connections.length} cables`)}
async function activateGraph(){const graph=compilePatchGraph(history.state,registry);await engine.applyCompiledGraph(graph);return graph}
function note(e){engine.sendNote(e)}
function loadPreset(id){const preset=getFactoryPreset(id);compilePatchGraph(preset.patch,registry);history.apply({type:'loadPatch',patch:preset.patch});log.push('info','factory preset loaded',{preset:id});render();rebuildIfRunning()}
function populatePresets(){const select=$('#preset-select');select.innerHTML='';for(const p of factoryPresets){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;select.append(o)}select.value='basic-subtractive';select.onchange=()=>loadPreset(select.value)}
export async function bootApp(){registry=createRegistry();for(const d of coreDefinitions)registry.register(d);let start=defaultPatch;try{start=loadLocal()||defaultPatch}catch{}history=new HistoryController(start);engine=new AudioEngine(t=>{$('#meter').textContent=`Peak ${(t.peak??0).toFixed(3)} · RMS ${(t.rms??0).toFixed(3)} · Voices ${t.voices??0}`});scheduler=new VisualizationScheduler();populatePresets();render();renderKeyboard($('#keyboard'),note);$('#master-volume').oninput=e=>{const master=history.state.modules.find(m=>m.type==='master');if(!master)return;const value=Number(e.target.value);history.apply({type:'setParam',id:master.id,param:'gain',value});engine.setParameter(master.id,'gain',value)};$('#master-mute').onclick=()=>{masterMuted=!masterMuted;engine.setMuted(masterMuted);syncMasterControls()};keyboard=new ComputerKeyboard(note);keyboard.attach(window);$('#audio-start').onclick=async()=>{await activateGraph();$('#audio-start').textContent='Audio Running';log.push('info','audio started')};$('#panic').onclick=()=>{engine.panic();log.push('warn','panic invoked')};$('#undo').onclick=()=>{history.undo();render();rebuildIfRunning()};$('#redo').onclick=()=>{history.redo();render();rebuildIfRunning()};$('#save-patch').onclick=()=>{saveLocal(history.state);download('visualsynth-patch.json',serializePatch(history.state));log.push('info','patch saved')};$('#load-patch').onclick=()=>$('#patch-file').click();$('#patch-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const{patch}=deserializePatch(await file.text());compilePatchGraph(patch,registry);history.apply({type:'loadPatch',patch});render();await rebuildIfRunning();log.push('info','patch loaded')}catch(err){alert(`Could not load patch: ${err.message}`);log.push('error','patch load failed',{message:err.message})}e.target.value=''};midiState=await connectMidi(note);$('#midi-status').textContent=`MIDI: ${midiState.available?'ready':midiState.reason}`;$('#copy-diagnostics').onclick=async()=>{const text=JSON.stringify(diagnosticsDocument(),null,2);try{await navigator.clipboard.writeText(text);status('Diagnostics copied')}catch{status('Clipboard unavailable; use Download')}};$('#download-diagnostics').onclick=()=>download('visualsynth-diagnostics.json',JSON.stringify(diagnosticsDocument(),null,2));const startVisuals=()=>{if(!engine.analyser)return;scheduler.add('scope',()=>drawWaveform($('#scope'),engine.analyser),{fps:30,visible:()=>document.visibilityState==='visible'});scheduler.add('spectrum',()=>drawSpectrum($('#spectrum'),engine.analyser),{fps:20,visible:()=>document.visibilityState==='visible'});scheduler.start()};$('#audio-start').addEventListener('click',()=>setTimeout(startVisuals,0),{once:true});log.push('info','application booted',{midiAvailable:midiState.available})}
bootApp().catch(err=>{console.error(err);status(`Startup error: ${err.message}`);log.push('error','startup failure',{message:err.message})});
